#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v4
# autospec commit: e738c51
#
Name     : R-bdsmatrix
Version  : 1.3.7
Release  : 54
URL      : https://cran.r-project.org/src/contrib/bdsmatrix_1.3-7.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bdsmatrix_1.3-7.tar.gz
Summary  : Routines for Block Diagonal Symmetric Matrices
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: R-bdsmatrix-lib = %{version}-%{release}
Requires: R-bdsmatrix-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package lib
Summary: lib components for the R-bdsmatrix package.
Group: Libraries
Requires: R-bdsmatrix-license = %{version}-%{release}

%description lib
lib components for the R-bdsmatrix package.


%package license
Summary: license components for the R-bdsmatrix package.
Group: Default

%description license
license components for the R-bdsmatrix package.


%prep
%setup -q -n bdsmatrix
pushd ..
cp -a bdsmatrix buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709417928

%install
export SOURCE_DATE_EPOCH=1709417928
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-bdsmatrix
cp %{_builddir}/bdsmatrix/inst/COPYRIGHTS %{buildroot}/usr/share/package-licenses/R-bdsmatrix/6a2cdacc94646a3c2d959c2ea0818f8e8df6555c || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-va/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bdsmatrix/COPYRIGHTS
/usr/lib64/R/library/bdsmatrix/DESCRIPTION
/usr/lib64/R/library/bdsmatrix/INDEX
/usr/lib64/R/library/bdsmatrix/Meta/Rd.rds
/usr/lib64/R/library/bdsmatrix/Meta/features.rds
/usr/lib64/R/library/bdsmatrix/Meta/hsearch.rds
/usr/lib64/R/library/bdsmatrix/Meta/links.rds
/usr/lib64/R/library/bdsmatrix/Meta/nsInfo.rds
/usr/lib64/R/library/bdsmatrix/Meta/package.rds
/usr/lib64/R/library/bdsmatrix/NAMESPACE
/usr/lib64/R/library/bdsmatrix/NEWS.Rd
/usr/lib64/R/library/bdsmatrix/R/bdsmatrix
/usr/lib64/R/library/bdsmatrix/R/bdsmatrix.rdb
/usr/lib64/R/library/bdsmatrix/R/bdsmatrix.rdx
/usr/lib64/R/library/bdsmatrix/help/AnIndex
/usr/lib64/R/library/bdsmatrix/help/aliases.rds
/usr/lib64/R/library/bdsmatrix/help/bdsmatrix.rdb
/usr/lib64/R/library/bdsmatrix/help/bdsmatrix.rdx
/usr/lib64/R/library/bdsmatrix/help/paths.rds
/usr/lib64/R/library/bdsmatrix/html/00Index.html
/usr/lib64/R/library/bdsmatrix/html/R.css
/usr/lib64/R/library/bdsmatrix/include/bdsmatrix.h
/usr/lib64/R/library/bdsmatrix/include/bdsmatrix_stub.h
/usr/lib64/R/library/bdsmatrix/tests/backsolvetest.R
/usr/lib64/R/library/bdsmatrix/tests/backsolvetest.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/bdstest.R
/usr/lib64/R/library/bdsmatrix/tests/bdstest.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/chtest.R
/usr/lib64/R/library/bdsmatrix/tests/chtest.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/chtest2.R
/usr/lib64/R/library/bdsmatrix/tests/chtest2.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/corner.R
/usr/lib64/R/library/bdsmatrix/tests/corner.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/corner2.R
/usr/lib64/R/library/bdsmatrix/tests/corner2.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/gtest.R
/usr/lib64/R/library/bdsmatrix/tests/gtest.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/gtest2.R
/usr/lib64/R/library/bdsmatrix/tests/gtest2.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/matrix.R
/usr/lib64/R/library/bdsmatrix/tests/matrix.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/nullr.R
/usr/lib64/R/library/bdsmatrix/tests/nullr.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/reconcile.R
/usr/lib64/R/library/bdsmatrix/tests/reconcile.Rout.save
/usr/lib64/R/library/bdsmatrix/tests/tinv.R
/usr/lib64/R/library/bdsmatrix/tests/tinv.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/bdsmatrix/libs/bdsmatrix.so
/usr/lib64/R/library/bdsmatrix/libs/bdsmatrix.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-bdsmatrix/6a2cdacc94646a3c2d959c2ea0818f8e8df6555c
